# Generated by Django 3.2.4 on 2021-06-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='building_info',
            fields=[
                ('building_id', models.CharField(max_length=20)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fuel', models.TextField(max_length=20)),
                ('unit', models.CharField(max_length=3)),
            ],
        ),
    ]
